# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target ‘sanxi’ do

pod 'CYLTabBarController'
pod 'Masonry', '~> 1.0.1'
pod 'YTKNetwork', '~> 1.1.0'
pod 'DBCamera', '~> 2.4.1'
pod 'IQKeyboardManager', '~> 4.0.3'
pod 'SDCycleScrollView','~> 1.64'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'HMSegmentedControl', '~> 1.5.3'
pod 'MJRefresh', '~> 3.1.12'
pod 'FMDB'
pod 'CircleProgressBar', '~> 0.32’
pod 'NJKWebViewProgress'
pod 'JPush'
pod 'CTCheckbox', '~> 0.0.5'
end

post_install do |installer|
    copy_pods_resources_path = "Pods/Target Support Files/Pods-sanxi/Pods-sanxi-resources.sh"
    string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
    assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'
    text = File.read(copy_pods_resources_path)
    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
    File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
end
